### ISSUE TITLE
Demand control slider not working

### ISSUE THREAD

**Issue by Safs** [kamaradclimber/heishamon-homeassistant#124]
- Home Assistant version: 2023.10.1
- This integration version  1.2.3

**Describe the bug**

When I try to move slider of demand control, then nothing hapaning, only showed this error:

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/e0581b54-b508-4d0c-bed2-1d80466d234b)

I already activated "Emulate optional PCB" and demand control option in Aquera panel.

When I send command directly within MQTT, then everything working well.

**Comment by kamaradclimber** [comment]
Hello, thanks for reporting this.

I think this error is purely on the integration side (not your configuration) otherwise we would see a different error.
It is a bit hard for me to debug this since I don't have the same setup, I'll try anyway.

By any chance do you have error log in HA logs? I think it would help me to understand where the issue is.

**Comment by Safs** [comment]
is tihis ok?

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:906
First occurred: October 10, 2023 at 16:32:41 (54422 occurrences)
Last logged: 21:32:05

Failed to set state, fall back to unknown
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 906, in _async_write_ha_state
    hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1687, in async_set
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1264, in __init__
    validate_state(state)
  File "/usr/src/homeassistant/homeassistant/core.py", line 184, in validate_state
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state with length 376. State max length is 255 characters.
`

**Comment by kamaradclimber** [comment]
That might be it, thanks for providing this.

I'm a bit puzzled by `First occurred: October 10, 2023 at 16:32:41 (54422 occurrences)` (the 54k occurences feels it has been going on for a long time).

**Comment by Safs** [comment]
Seems it trigered every second since I touch that slider..
I try to restart HA.

**Comment by kamaradclimber** [comment]
Do you get more info in the logs if you set the integration to debug log level?

It would look like this in your configuration file:
```
logger:
  default: warning
  logs:
    custom_components.aquarea: debug
```

**Comment by kamaradclimber** [comment]
Ok I succeeded to reproduce it:
- it happens when trying to update the slider from the normal view. I don't have the same logs than you (I don't have any log)
- it does not happen when trying to update the slider when the entity modal is opened 

I think it is linked to the fact we define a default value to None and that it's never updated because there is no mqtt topic to subscribe to get values.

I'll try a few workarounds

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/503537/ca93f244-820f-4d9f-9d3a-8d6d090a42b8)

**Comment by kamaradclimber** [comment]
https://github.com/kamaradclimber/heishamon-homeassistant/pull/126 should fix it, I'll add it in https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.2.4
