### ISSUE TITLE
Add additional entities from mqtt messages

### ISSUE THREAD

**Issue by backupandforkacc** [kamaradclimber/heishamon-homeassistant#162]
**Is your feature request related to a problem? Please describe.**

There are two entities, which are in mqtt, but not in homeassistant application.
panasonic_heat_pump/main/Buffer_Tank_Delta => TOP113
panasonic_heat_pump/main/Z1_Water_Temp = > TOP56

**Describe the solution you'd like**

Adding all entities from mqtt to home-assistant dashboard

**Describe alternatives you've considered**

**Additional context**

**Comment by geduxas** [comment]
Both values are in heishamon.

**Comment by kamaradclimber** [comment]
Hello, thanks for the report.

TOP113 is exposed (as you can see on https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/definitions.py#L583-L595) but is disabled by default since it is a non common setup. You should be able to see it by going on your `/config/integrations/dashboard` page, selecting heishamon, and open the relevant device page (related entity will be hidden behind "entities not shown", click on it and enable it).
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/503537/24e480bc-0563-4f68-9532-d70250159df0)


TOP56 is exposed under an entity called "Aquarea Zone1: Actual Temperature"
