### ISSUE TITLE
COP when defrost is in action

### ISSUE THREAD

**Issue by Safs** [kamaradclimber/heishamon-homeassistant#181]
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0
- This integration version: 1.5.1

**Describe the bug**

When defrost mode is activated, COP must be to disabled, because of unreal values. In defrost mode calculation of COP is not necessary, because heat production is not in action.

**Comment by geduxas** [comment]
I was always curious, do Panasonic add that in it's own COP average or not? Because during defrost, remote controller shows COP too!. 

also from another perspective, maybe COP should go negative direction? or calculated to Cool COP?

**Comment by Safs** [comment]
This values exist very short time, therefore, I thing, there is very small impact of those on average values.

**Comment by kamaradclimber** [comment]
Could you describe what you mean by "unreal" values.
Here is what I can see during defrost:
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/503537/30499265-ff51-40f1-a085-d90fcdc63732)
(green is defrost state, yellow is  COP)

**Comment by PGnl** [comment]
Actually, any energy used for defrost taken from from the water AND the energy used by the electric heater are negative COP.

I generate my COP on a per day basis by taking the positively generated heat, reducing that by the heat taken from the water.
Easiest is to allow heat power to go negative and then using the daily sum.

This is then divided by the combined total electric power consumption of the day ( both by the heat pump and the electric additional heater used for defrost).
This is an daily average COP that should be pretty exact and can also be used for COP values of the year. 

note that I do this using node red. 
also, I have adjusted my sensors by activating the pump in the menu without starting the heat pump.
The sensors should then, after some time, read the same temp or be adjusted. 
 I did this with an outside temp of some 10-15 degrees, otherwise you loose to much energy via the heatpump.

**Comment by Safs** [comment]
That is  not solution for realtime data.  And in defrost mode COP is always -1, because energy is taken from system inside only (water). 
Did you compare your calculated COP with Panasonic fixed data? Is there big difference?

**Comment by Safs** [comment]
Still not working...
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/f74120d7-d16c-46d5-a502-a6d0d6280a6a)

**Comment by kamaradclimber** [comment]
@Safs I’ve seen your comment saying it’s not working but it has disappeared. Could you confirm whether it works for you please?

**Comment by Safs** [comment]
At first I noticed that it didn't work, but then I noticed that I didn't have the latest version installed, when I installed it, I see that everything works now.
Sorry!

**Comment by kamaradclimber** [comment]
No pb!

**Comment by Safs** [comment]
Seems it stopped working...
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/f37c5ced-e7f0-4639-864c-94164489d35a)

**Comment by kamaradclimber** [comment]
Indeed there is a bug, I'll fix it sorry for all churn!

**Comment by curzon01** [comment]
> And in defrost mode COP is always -1, because energy is taken from system inside only (water).

as @Safs already mentioned COP is the ratio of the cooling or heating energy generated to the electrical energy used, regardless of whether the heat pump adds or removes it. 

I always use the absolute values of energy to calculate the COP, this also works if you use the heat pump for cooling.

> but in defrost mode, compressor do not produce heat at all, therefore, any COP value in this mode is unreal.

However, the last part is also not always the case and is only true regarding to the compressor, but this is not the only energy source for a heat pump:
If outlet temperature is too low, additional interal heater is used for defrosting, and this costs additional electrical energy (you can switch this function off, but then you risk the heat pump coming to a standstill due to error H75):

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/6636844/aa77395f-6a21-4f95-a9cb-e7ef81be23a2)

> Those values make peaks in graph, thats make less visualy good look this graph.

Only to avoid peaks in graphics should you use other options and not change the data basis for this.

**Comment by kamaradclimber** [comment]
@curzon01 what would you suggest?

**Comment by curzon01** [comment]
As already explained for the definition of COP, this value cannot be negative, as this would mean by definition that the heat pump generates electrical energy and feeds it back into the grid.

The current decision to simply delete such high COP values (defrost, COP > 15) is simply wrong, just because someone realize that they are for a short term (what kind of span is that?, 10 ms, 5 sec. 3 minutes...) on own systems. This can be very different on other systems and climate situations.
So I do not think it is correct to manipulate the calculated values in any way for aesthetic reasons (plot) and only because very high COP values (which are not wrong) can arise for a short time.

My pseudo-code (unfortunately I don't have time to set a PR in the short time available) for the total COP would therefore be (might be it was before, I don't know the valuesy[x:y] values):

```
production = "main/Heat_Power_Production" + "main/Cool_Power_Production" + "main/DHW_Power_Production"
consumtion = "main/Heat_Power_Consumption" + "main/Cool_Power_Consumption" + "main/DHW_Power_Consumption"
cop = production / consumption if consumption != 0 else 0
```

**Comment by geduxas** [comment]
Just don't calculate cop for defrost, and that's it.. 
By judging of 3 states.. while 3way valve heating DHW, calculate cop for TANK, in opposite way, calculate for heating.. in defrost state don't do any calculations leave zero.. don't know why it should be negative. 

While defrost'ing Panasonic itself shows high COP rate, but it's unknown for me does it add it to overall cop.. 

Defrost routine is simply switching from heating mode to cooling mode in hi performance.. and heat for internal heater or heated system is used to prevent damage for internal heat exchanger.. heat is not used for defrost directly..

**Comment by curzon01** [comment]
> heat is not used for defrost directly..

that's not true

**Comment by kamaradclimber** [comment]
What do you think of https://github.com/kamaradclimber/heishamon-homeassistant/pull/193

**Comment by kamaradclimber** [comment]
Regarding filtering values > 15, it's true it's mostly for aestheticism. However, my assumption is that those values come because we have some (small) lag between production and consumption topics (they can't be updated simultaneously) so we filter those values.

**Comment by curzon01** [comment]
> What do you think of #193

As I said,the conditions are not always so ideal that the heat pump can manage the defrost completely with external heat energy alone, so it is wrong to have an exception for the defrost mode - I would be cheating myself

You can do it this way, but it's not usable for people like myself.

**Comment by curzon01** [comment]
> However, my assumption is that those values come because we have some (small) lag between production and consumption topics (they can't be updated simultaneously) so we filter those values.

I have checked my measured values again, these are real values:
In addition to heishamon, I use an external heat and power meter that stores the values faster then a second when it changes. Such exceptions are normal and sometimes are up to 240 for a very short time - but normally they are around 17-50. As I said, these are values from my separate heat meter and power meter, not from Panasonic or heishamon.

**Comment by Bucky2k** [comment]
For what it's worth I'm fine with either solution (old and new). The limit of 15 makes sense as it's just to keep the graphs from scaling down too much. But that was already the case. Now suppressing COP during defrost - I do like the smoothening effect on the graph but again not really necessary


Also my measured COP from electricity meter (S0) and heat meter has spikes due to time delays (electricity off, but heat still coming). Of course I don't want to see high spikes when 20 Watts electricity are measured during 5KW heat flow still being present after pump shutdown. Those COP values I limit for example already at 12

![Screenshot_20240121_174738_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/ec3aae3e-4008-448b-9d83-29fd298ce022)

**Comment by Safs** [comment]
As mentioned above, just do not calculate COP in defrost mode, that it.

**Comment by Bucky2k** [comment]
> As mentioned above, just do not calculate COP in defrost mode, that it.

Only works for the Aquarea COP. The measured COP is delayed. And as @curzon01 mentioned, the suppression does not fit for everyone or at least is not yet agreed to be the better way. I will be fine with either, only cosmetics

**Comment by Safs** [comment]
Then limit  value to 5 or 6, because technically (by specification of Panasonic) is not possible to pruduce more than this.

**Comment by Bucky2k** [comment]
> Then limit value to 5 or 6, because technically (by specification of Panasonic) is not possible to pruduce more than this.

Not really. I have seen continuous COP above 9 (even measured) during cooling, shortly even above 10 and consistent above 5 is also no magic (10°C Outside temp, 29°C Outlet).

**Comment by Bucky2k** [comment]
Even at 4°C outside I reach COP >5
![Screenshot_20240121_195116_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/a6c15b6c-6eaf-430c-b120-8145c473d3d2)

**Comment by Safs** [comment]
As you see, mesured is not more than 6.

**Comment by Safs** [comment]
Anyway, that is fare away from 15.

**Comment by Bucky2k** [comment]
Yes, 12 I figured for my case plenti as threshold. Regarding measured not more than 6: Of course, 4°C outside! Of course there is a better one at 10-15°C. And even if the measured is slighly lower than the one from Aquarea, the integration should not artificially limit the display. For cooling the COP can be much higher
