### ISSUE TITLE
Consumption data is "unknown"

### ISSUE THREAD

**Issue by Safs** [kamaradclimber/heishamon-homeassistant#182]
Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240104.0

This integration version: 1.5.1

Why consumption data is "unknown"?

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/520e2b67-ce52-41fa-99dd-bb0241838094)

**Comment by Bucky2k** [comment]
Had the same, but already 2-3 weeks ago. I needed to completely reinstall Heishamon integration (incl. deletion of entities), as my entities still contained "energy" rather than "power" in their naming. Only the name tag was corrected, not the entity name itself

**Comment by Safs** [comment]
Yes, the situation has been there for some time.

**Comment by Bucky2k** [comment]
Not sure of this breaking change can be easily catched. On Heishamon all names have changed to power - so the entities need to be renamed in HA. Can this be automated?

**Comment by Safs** [comment]
So, what I need to do? I need rename those entities?

**Comment by Bucky2k** [comment]
I uninstalled the integration from HACS, manually deleted remaining associated entities manually (I think there were some) and then reinstalled after a fresh HA restart. However, counters are reset to 0

**Comment by kamaradclimber** [comment]
In theory, counters should have been upgraded when moving from heishamon 3.0 to 3.2+. However in case of issue, indeed, reinstallation of this integration helps (or even better: clean of mqtt messages in your broker).

I'm trying to have backward compatible code but lack of testing of this integration leads to bugs indeed, sorry!
I'd be happy to solve it. Can you provide:
- heishamon version
- the relevant mqtt topics you have in your broker at the moment?

**Comment by Safs** [comment]
heishamon version 3.2.3

How to see relevant mqtt topics?

**Comment by kamaradclimber** [comment]
You have to use a software such as "MQTT Explorer" which allows to explore the content of your MQTT broker.

**Comment by Safs** [comment]
What data do You need?

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/7047586/b0096605-3fb7-4ead-88af-6ca1ca378932)

**Comment by Bucky2k** [comment]
I would like to help, but I don't know what you are up to Safs...

In the past the mqtt stack contained the words "power" I side the relevant topics. Equally, also the HA entity names were named accordingly.

Now it the names changed to "power" on the MQTT topics and it might be good to identify and clear the old topics. Those resulted into double counting and wrong COP/Power readings for a while, but I thought this error is now catched by the integration automatically. 


But the issue at hand is different. The entity names in HA never changed - they were still containing "energy" in the name and therefore COP calculation and the counters for kWh did not work anymore. For this you have to delete and reinstall the Heishamon integration from HA - that's it

**Comment by Bucky2k** [comment]
E.g. what is the name of your entity: Aquarea Heat Power Produced ?

It should be "sensor.panasonic_heat_pump_main_heat_power_production"

It might be still "sensor.panasonic_heat_pump_main_heat_energy_production" (or similar). In that case you need to re-install and the counters start working again

**Comment by Safs** [comment]
Yes, it is "sensor.panasonic_heat_pump_main_heat_energy_consumption"
But if I re-install hesiamon, then I will lost all my history data?

**Comment by Bucky2k** [comment]
Yes, that happened to me and I have not found a way to reset the counters to the old value again (will always be overwritten again after a short time :(

**Comment by Safs** [comment]
Then that is not solution for me. I do not want to lose 2 years data.
As I understand, problem is at my side, and that is not an plugin isusse.

**Comment by kamaradclimber** [comment]
> What data do You need?
> 
> ![image](https://private-user-images.githubusercontent.com/7047586/296166658-b0096605-3fb7-4ead-88af-6ca1ca378932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjc1NzMsIm5iZiI6MTcwNTA2NzI3MywicGF0aCI6Ii83MDQ3NTg2LzI5NjE2NjY1OC1iMDA5NjYwNS0zZmI3LTRlYWQtODhhZi02Y2ExY2EzNzg5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMTM0NzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYyNjkxOGEwYjFjMjk1NzEzMjBjYjE2OGU5NmVlZTE4NDNkYzE3ZGJjMzlmNDViZjdlNWU1YmU3YmUxMmQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuUUEbWKF65gAUKR086YjvjwbgJoSdQfpYgnCBSDxb8)

You should open the `main` section and delete everything containing "energy".
In case of doubt this is quite safe to delete all topics, they should be recreated by heishamon on next change (or at worst every 5 minutes).

I think it should fix the unknown you face.
Otherwise, please look at your integration logs, maybe there are errors.

**Comment by Bucky2k** [comment]
But @kamaradclimber, now I want to know: Change on MQTT topics is clear, but did you ever adapt the integration, to actively and retrospectively change the entity naming in HA? I think not and the problem seems to be, that the counters of recent versions of your integration are posting "unknown" as they are looking for entities with the new name oder am I mistaken? Again, entity name, not MQTT topic name

**Comment by Bucky2k** [comment]
> Are we talking about the same entities? For instance the "Pump total consumption" entities is not referring to other entities but directly to mqtt topics ([source](https://github.com/kamaradclimber/heishamon-homeassistant/blob/59ca622be4b9b0d13704e1d586ddb66117333f26/custom_components/aquarea/sensor.py#L113) )

Not sure to be honest, I am.not exactly sure how the integration is creating the entity during first installation.

But before the changes on MQTT heishamon side, one of the riemann integral entities created in HA was named "sensor.aquarea_heat_energy_consumed_total". At some point after updates, the integration showed "unknown" for heat power consumed total. I guess the stock dashboard was looking for "sensor.aquarea_heat_power_consumed_total", but in HA the only entity name was still present. Deinstalling and reinstalling the integration set up the entity name following the same new name as the MQTT topics (e.g. sensor.aquarea_heat_power_consumed_total). Since then, I see the sensor values (current and totals) again

**Comment by kamaradclimber** [comment]
Indeed, you’re right, I forgot about riemann integrals (https://github.com/kamaradclimber/heishamon-homeassistant/blob/59ca622be4b9b0d13704e1d586ddb66117333f26/custom_components/aquarea/sensor.py#L184-L195).


To see the source, use developer tools:
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/503537/11662b68-b3f8-45e4-836c-6e7fe84c516e)

**Comment by MEKadan** [comment]
1. I have the same problem
 
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/66167932/d1636b9a-02cb-44a6-b2c3-3f7a2820a715)


2. I do not have any "energy" MQTT topics.  They are all like this

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/66167932/c6918fc9-cd3d-4917-a77a-fba15da614cc)


In the sensor section there are e.g.
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/66167932/e2e64a90-b6ab-44fa-9ea9-b8d361590324)

...which take the entity name in HA in a form like this: `sensor.panasonic_aquarea_main_heat_energy_consumption` and `sensor.panasonic_aquarea_main_heat_energy_production`  (That  panasonic_aquarea -prefix comes from my Heisha Monitor original setting of my `Mqtt topic base`)


I actually did not even notice this change of behaviour earlier, because I have not used these provided Riemann integrals (which do not work currently). Instead of that, I have used these 'energy' entities to create my own Riemann integrals (and utility meters based on those, if that matters). I also calculate the COP based on these.

Still, it is not clear to me what is the outcome of all the discussion above? 

What do I need to do? Or is there an update coming up sometimes in the future because of these "forgotten Riemann integrals"?

Actually, I probably don't even need these currently non-working sensors, so I could be fine like this, but it is a somewhat trivial solution just to leave it be...

**Comment by Bucky2k** [comment]
If you don't care about the values of those integrals, just deinstall/reinstall Heishamon. Entities will change from having "energy" in the naming to "power" and everything works again

**Comment by MEKadan** [comment]
> If you don't care about the values of those integrals, just deinstall/reinstall Heishamon. Entities will change from having "energy" in the naming to "power" and everything works again

Yes, I noticed from above that would be one possible way to do it, however, it is unclear to me, what as a whole will change (maybe some other entities as well, and which I might be using?) and lastly, do I loose some of my history data?

**Comment by MEKadan** [comment]
> Entities will change from having "energy" in the naming to "power" and everything works again

If by this you mean my sensors like  `sensor.panasonic_aquarea_main_heat_energy_consumption` and `sensor.panasonic_aquarea_main_heat_energy_production` will change, they are exactly the ones I use to calculate my Riemanns and utility meters which means I need to use a different source sensors for them. Won't this cause a loss of history data?

Some time again, when there was a change from these `energy `to power `sensors`, I think it was done so, that the old `energy ` sensors and new `power `sensors were summed, and the resulting sensor was still the old `energy `sensor and because of summing, could hold both old and new data?

**Comment by Bucky2k** [comment]
You need your Riemans to adopt the new source sensor. But their value remains (do backup for rollback before just in case)

**Comment by kamaradclimber** [comment]
Bucky2k is right: if you uninstall/reinstall the integration, your own riemann counters will not be impacted (you'll just need to change the source sensor).

**Comment by MEKadan** [comment]
How do I actually uninstall this ? I f I go to HACS - Heishamon and from 3 dots on the upper right corner 3 dots select `Remove`, I get this: 
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/66167932/42ab688c-f3d6-4e9d-a85e-7b1f91661603)

If I select `Navigate`, it takes me to `Settings `-> `Integrations ` page and selecting Heishamaon it gives

![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/66167932/4b7801da-6be0-4513-af8b-843977d0cb6d)

So, do I delete it from there first? And then from HACS? 

Installation as per https://github.com/kamaradclimber/heishamon-homeassistant/ ?

Do I need to manually delete some entities etc.?

**Comment by kamaradclimber** [comment]
Yes indeed:
- delete the integration from settings->integration->heishamon
- delete it from hacs
- reinstall from hacs
- your heishamon install will be autodetected you just have to accept the auto-detection


You should not have to delete any entity.

**Comment by MEKadan** [comment]
OK, thanks! All set now.

**Comment by kamaradclimber** [comment]
I'll close that issue but feel free to put a comment if there are any news

**Comment by Bucky2k** [comment]
Hmm, since ~ 10 days the Riemann integral sensors for the totals went unknown. After I did a HACS Heishamon reinstall, they also don't come back. Have they been removed from the integration?

![Uploading Screenshot_20240703_233947_Home Assistant.jpg…]()

**Comment by Bucky2k** [comment]
![Screenshot_20240703_233947_Home Assistant](https://github.com/kamaradclimber/heishamon-homeassistant/assets/67497826/7dcbbe2a-8260-463d-9d23-9f0577205e26)

**Comment by kamaradclimber** [comment]
I think the issue is a bit different, it was reported in #222 and is due to a change in the constructor of Riemman Integral sensor in HA 2024.7. Fixed in 1.9.2. 
Please open a new issue if it is not fixed.
