### ISSUE TITLE
[custom_components.aquarea.climate] [HEAT] Target temperature is not within expected range, this is suspicious

### ISSUE THREAD

**Issue by Binifada1956** [kamaradclimber/heishamon-homeassistant#240]
1.41

- Home Assistant version 2024.8.2

I dont know is a Bug. I constantly get this message:

[custom_components.aquarea.climate] [HEAT] Target temperature is not within expected range, this is suspicious

Why?

**Comment by kamaradclimber** [comment]
Hello, thanks for the report. Could you update to version 1.12.4 of this integration and report the log line again please?

**Comment by Binifada1956** [comment]
New Message:
2024-09-07 17:18:43.689 WARNING (MainThread) [custom_components.aquarea.climate] [HEAT] Target temperature is not within expected range, this is suspicious. 5.0 should be within [20,55]

My Temperatures 26 °C low and 35 °C high are between in your Range 20…55 🤷‍♂️

**Comment by kamaradclimber** [comment]
Could you look at the mqtt topic `heishamon/main/Z1_Heat_Request_Temp` (and same for Z2) please?
Also are you using the direct, room or compensation mode of your heatpump?

**Comment by geduxas** [comment]
> Could you look at the mqtt topic `heishamon/main/Z1_Heat_Request_Temp` (and same for Z2) please? Also are you using the direct, room or compensation mode of your heatpump?

Compensation curve, always will be -5+5 range

**Comment by Binifada1956** [comment]
I use Compensation Curve and believe Z1_ Heat Request_Temp ist wrong.

Z1_Heat_Curve_Target_High_Temp and Z1_Heat_Curve_Target_Low_Temp limit the Compensation Curve.

Z2 is not used.

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/473fd6d3-f2ac-4922-b465-152de5763823">

**Comment by Binifada1956** [comment]
Morning, another Message:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.aquarea.climate
Quelle: custom_components/aquarea/climate.py:338
Integration: HeishaMon (Dokumentation, Probleme)
Erstmals aufgetreten: 7. September 2024 um 22:33:39 (105 Vorkommnisse)
Zuletzt protokolliert: 07:13:56

[HEAT] Target temperature is not within expected range, this is suspicious. 5.0 should be within [-5,5]

Z1_Heat_Request_Temp is Zero, see screenprint before.

**Comment by Binifada1956** [comment]
I think ‘ZoneTemperatureMode’ Direct and Compensation should be swapped, right?

________________________________________________________
if mode == ZoneTemperatureMode.COMPENSATION:
            self._attr_min_temp = -5
            self._attr_max_temp = 5
            self._attr_target_temperature_step = 1
        elif mode == ZoneTemperatureMode.DIRECT:
            if self.heater:
                self._attr_min_temp = 20
                self._attr_max_temp = 55

**Comment by kamaradclimber** [comment]
Thanks for the details.

> [HEAT] Target temperature is not within expected range, this is suspicious. 5.0 should be within [-5,5]
I'll fix this case, it should not warn of course.

I'm a bit confused by several items:

>My Temperatures 26 °C low and 35 °C high are between in your Range 20…55 
- are you referring to the low and high temp? You cannot control them with the climate entity (you can only control the "shift" value which -5/+5)

- your screenshot shows a target temp of 0 for Z1 (which means a shift of 0) but the warning shows 5. Are you trying to set the shift to +5 ?


Overall, I'm not sure I understand what happens but it seems the integration code thinks you are using direct mode (that would explain the first warnings you reported) and later thinks you are using compensation mode (which is true).
I guess it could be because the integration starts by assuming direct mode and guess the proper mode when receiving relevant mqtt messages.
If that's true, I would assume you see:
- a first message with `[20,55]` right after HA startup
- then a message with `[-5,5]` each time you try to update the shift via climate entity.

I'll try two things to improve the situation
- short-term: remove the warning until the temperature mode is not known for sure (i.e after receiving a first mqtt message)
- mid-term: store the mode in a persistent manner to avoid "guessing". This can be done by temperature mode does not change often (it requires some reconfiguration on the heatpump) so it's ok to assume it has not changed after a HA restart).

**Comment by Binifada1956** [comment]
yes, its right, the first Message [20/55] comes at the beginning. Later Message [-5/5].
The Heatpump always run in the Compensationmode.

I believe DIRECT and COMPENSATION are mixed up in your programme code?

„your screenshot shows a target temp of 0 for Z1 (which means a shift of 0) but the warning shows 5. Are you trying to set the shift to +5 ?“
>>> Z2_Heat_Request_Temp is +5, but Zone2 ist not in use 🤷‍♂️

**Comment by kamaradclimber** [comment]
Thanks for the precision about Z2.

I'm not sure to understand why direct and compensation would be mixed up.
In compensation mode, you can only change the shift value (-5/+5) so "target temperature" (in mqtt) is the shift.
The heatpump used that shift in addition to the compensation curb to compute the real target temperature (but it's not exposed).
So in compensation mode, acceptable values are in the range of -5..5.

**Comment by kamaradclimber** [comment]
Version 1.13.0 should be better and should not display any warning anymore. Could you test it and let me know if you encounter any issue?

**Comment by Binifada1956** [comment]
No more Messages 👍. Thanks for your Work.
