### ISSUE TITLE
Problems with climate

### ISSUE THREAD

**Issue by geduxas** [kamaradclimber/heishamon-homeassistant#47]
Hello, after restarting HomeAssistant i have lost ability to use climate component. 

![Screenshot_2022-11-10-09-14-54-19_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/18700450/201025282-8783f00e-2a28-4e8f-af6d-fce6c66d820d.jpg)

![Screenshot_2022-11-10-09-14-33-41_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/18700450/201025313-c4b46c18-fda8-4f97-94ef-938377b8e064.jpg)

Don't know why it tried to change to direct mode, i never used direct mode on my pump..
 
And it's happening everytime HA is restarted, and climate component is failing.
Tried to downgrade integration, issues are in all versions till 7.2. It's seams something changed in HomeAssistant, before everything worked.

**Comment by kamaradclimber** [comment]
Hello,

thanks for the report.
The warning is "expected" because we don't know what how heatpump is working at HA startup so we [apply the direct mode](https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/climate.py#L301) by default and later change it to the correct value based on the message sent by HeishaMon.
Two solutions for this:
- we could not log this as a warning, especially for the change triggered at initialization which is purely a way to have an consistent internal state
- it is also possible to store the state in HA between restarts and re-read it at startup but the code to do this is a bit more involved.

That being said, I don't see yet if this is related to your first issue which is more serious. I need to investigate (which version of HA do you have?)

**Comment by geduxas** [comment]
Here is mine HA version:
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

I think i am on latest version.

Warning i understand why it happening, but climate components would not start anymore.. it seams that HA after reboot remembers devices, and on intialize it tires to recreate them.. or maybe they are created and updated in same time. My heishamon MQTT retransmission  set to 5 sec.

**Comment by kamaradclimber** [comment]
While trying to reproduce I stumbled upon https://github.com/kamaradclimber/heishamon-homeassistant/pull/48 which is probably very close to your issue. I'll try to reproduce yours specifically.

**Comment by geduxas** [comment]
Thanks, it seams problem solved. After update, climate components start to work.
