### ISSUE TITLE
Not all sensor values appear in autogen dashboard

### ISSUE THREAD

**Issue by Bucky2k** [kamaradclimber/heishamon-homeassistant#50]
Hi,

first of all - great work! In my case not all entities show up the autogen dashboard, e.g. quiet mode switch or compressor frequency. I can however add them manually to my dashboards. Is that on purpose?

Br

Bucky

**Comment by geduxas** [comment]
Indeed no quiet mode.. i think it's easy fix. But compressor frequency is showing. Do you have it in heishamon page?

**Comment by Bucky2k** [comment]
I would have to compare autogen and entities list, but I would estimate around 10 entities not appearing in the autogen dashboard. Heishamon is complete/all available. Also, I can find every value as entity including the correct value.

**Comment by Bucky2k** [comment]
Or maybe I have a conflict from the previous manual Heishamon configuration? E.g. I see the prefix for COP is still "xxx.aquarea_xxx" instead of "panasonic_heat_pump". Or is this the same on your side? Sorry, I have not yet reviewed the code here yet to check myself


![Screenshot_20221121_080334_Home Assistant](https://user-images.githubusercontent.com/67497826/202985947-52da9e05-5f0b-4f97-a65a-73e8666e8103.jpg)

**Comment by kamaradclimber** [comment]
Hello, thanks for the report.

If the list of missing entities contains: compressor current, compressor frequency, compressor operating hours, compressor start/stop count, last error, the reason is likely that HA does not add "diagnostic" entities in the "Everything" dashboard by default.
It might also be the case for the "configuration" entities.

To be honest, I think I should move more entities under configuration/diagnostic section to avoid cluttering the default interface, especially now that the climate entities exist (and are the main element to drive the heatpump). They are still easy to add manually to a dashboard of course.

**Comment by Bucky2k** [comment]
Agree, it seems I can find all entities under "device" and can click on "add to dashboard. 

However just as a note: Many other items to not appear, also the sliders for the heat delta, etc.

But minimizing autogen would make sense I guess. 

Btw, just checked: Aquarea as prefix is found here and there, for cop and energy consumption heat/dhw calculations. Could be adapted to panasonic_heat_pump for consistency
