### ISSUE TITLE
Heishamon online/offline

### ISSUE THREAD

**Issue by geduxas** [kamaradclimber/heishamon-homeassistant#65]
Today j suddenly got heishamon offline, and didn't noticed it anyhow.. just everything was reported in static values, and no changed are accepted..

Is it possible to implement online/offline or maybe sensors availability in integration?

**Comment by kamaradclimber** [comment]
Good idea.
We can implement it quite easily with a template that shows if we have received a message in the last xx minutes. Threshold is important here because it's configurable on HeishaMon side (300s by default to retransmit everything).

From what I understand, the need is more to be eventually aware of failure than detecting issues in a matter of seconds. So I guess a high threshold (like 10minutes) would be fine and cope with higher retransmit values.

**Comment by PGnl** [comment]
Agree, ten minutes should suffice.

**Comment by revin34** [comment]
Remember that we've LTW over MQTT. I'd use this topic to detect if heishamon is alive or not

![image](https://user-images.githubusercontent.com/50664921/207098141-51ef7326-f555-41a8-b4bc-4a524783cde4.png)

**Comment by geduxas** [comment]
Yes lwt is best option.

**Comment by kamaradclimber** [comment]
I'm hitting https://github.com/Egyras/HeishaMon/issues/289 during my tests but at least the patch is there
