### ISSUE TITLE
sensor.aquarea_cop

### ISSUE THREAD

**Issue by ttplayer** [kamaradclimber/heishamon-homeassistant#90]
I control now already a few days meanwhile 2 heat pumps with 2 Heishamon.
I use this integration for Homeassistant. For this thank you.....

While browsing the sensors I noticed **sensor.aquarea_cop** and **sensor.aquarea_cop_2**

But neither of the two sensors displays data!

Can I fix this or is this a bug in the integration?

![2023-05-24_070849](https://github.com/kamaradclimber/heishamon-homeassistant/assets/13061527/a01ecd8c-bfd8-4cce-9a50-29ac656e6c2d)

Sincerly Axel

**Comment by kamaradclimber** [comment]
Hello, thanks for the report!

https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/custom_components/aquarea/sensor.py#L164 defines COP with "production" divided by "consumption".

- production refers to `sensor.aquarea_energy_production`
- consumption refers to `sensor.acquarea_energy_production`

As far as I can see this will not be compatible yet with a second heatpump. I don't know how to fix this because all this relies on template sensors that are defined dynamically by the integration but we can refer to them only by id that can be changed by the user.

I'll try to think on how we could make this work.

In the meantime, could you provide the entity ids of energy consumption/production for both of your heatpump (I assume you've kept their default entity ids but I would prefer to be sure).

**Comment by ttplayer** [comment]
Thanks for your answer,
so that both Heishamon work with MQTT I had to assign different hostnames and MQTT Topic Base for each in the Heishamon settings.
**Heishamon** resp. **Heishamon1**
**panasonic_heat_pump** resp. **panasonic_heat_pump1**

The entity ids are

**sensor.aquarea_energy_consumption** resp. s**ensor.aquarea_energy_consumption_2**
**sensor.aquarea_energy_production** resp. **sensor.aquarea_energy_production_2**

**Comment by giedriuskilcauskas** [comment]
After upgrading to 2023.9 this part of implementation breaks integration completely due to a change:
![image](https://github.com/kamaradclimber/heishamon-homeassistant/assets/75305866/5bf331ea-106f-4bab-b329-a010d147ea0b)

I've manually removed that part from sensor.py file and it started working.

**Comment by kamaradclimber** [comment]
Any help on this specific issue would be greatly appreciated!

**Comment by kamaradclimber** [comment]
@ttplayer  could you try with the draft release [1.2.1?](https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.2.1) ?

**Comment by ttplayer** [comment]
Great news, thank you!

But unfortunately I have no idea how to install this pre-release.
Normally I update via hacs.

Best regards
Axel

Von: Grégoire Seux ***@***.***>
Gesendet: Sonntag, 8. Oktober 2023 14:38
An: kamaradclimber/heishamon-homeassistant ***@***.***>
Cc: ttplayer ***@***.***>; Mention ***@***.***>
Betreff: Re: [kamaradclimber/heishamon-homeassistant] sensor.aquarea_cop (Issue #90)


@ttplayer<https://github.com/ttplayer> could you try with the draft release 1.2.1?<https://github.com/kamaradclimber/heishamon-homeassistant/releases/tag/1.2.1> ?

**Comment by kamaradclimber** [comment]
Nevermind I've release a 1.2.2 with a bug fix and it's a public release, you can test it via hacs.
For another time: hacs can download pre-reloase if you ask it to download a specific version.

**Comment by ttplayer** [comment]
Ahhh, ok,

Thank you.

I’ll give it a shot tomorrow morning.

**Comment by ttplayer** [comment]
I've checked the behavior - COP Data is now there. Seems that the Integration ist working now with two Heatpumps.
Thanks for your Work!
